# データ解析(火1)
### 6回目

In [1]:
import pandas as pd

In [5]:
data = pd.DataFrame({'sex': ['男','女','女','男','男','女','女','男','男','女'],
                    'smoke': ['吸う','吸わない','吸う','吸う','吸わない','吸う','吸う','吸わない','吸う','吸わない']})

In [6]:
data

sex smoke
0   男    吸う
1   女  吸わない
2   女    吸う
3   男    吸う
4   男  吸わない
5   女    吸う
6   女    吸う
7   男  吸わない
8   男    吸う
9   女  吸わない

In [8]:
pd.crosstab(data.sex,data.smoke,margins=True)

smoke  吸う  吸わない  All
sex                 
女       3     2    5
男       3     2    5
All     6     4   10

In [9]:
import numpy as np

In [10]:
sexDigitize = np.array([1 if x == "女" else 0 for x in data.sex])
smokeDigitize = np.array([1 if x == "吸わない" else 0 for x in data.smoke])

In [11]:
sexDigitize

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [13]:
smokeDigitize

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1])

In [14]:
np.corrcoef(sexDigitize,smokeDigitize)

array([[1., 0.],
       [0., 1.]])

In [18]:
import scipy
from scipy import stats